
VIT:
  ETTA_PLUS:
    csp : True
    alpha : 0.2
    augmen : True
  ETTA:
    csp : False
    alpha : 0.2
    augmen : True



RESNET:
  ETTA_PLUS:
    csp : True
    alpha : 0.2
    augmen : True
  ETTA:
    csp : False
    alpha : 0.2
    augmen : True








